### ISSUE TITLE
RadSideDrawer broke the class processing if used on the initial page containing ngIf

### ISSUE THREAD

**Issue by ignaciolarranaga** [telerik/nativescript-ui-samples-angular#18]
It might seems a complicated scenario but it is quite simple, just try to use the SideDrawer on the initial page having some styling/conditions and voilà.

The reproduction is quite easy, here are the steps form the sample:
1) Point the example to the SideDrawerGettingStarted:
Change the route default on app/navigation/app.routes.ts:
```
    ...
    { path: "", redirectTo: "/SideDrawerGettingStarted", terminal: true },
    { path: "SideDrawerGettingStarted", component: SideDrawerGettingStartedComponent },
    ...
```
2) Add some style to app/sidedrawer/getting-started/getting-started.component.css:
```
...
.blue-style {
    color: blue;
}
```
3) Add some Label with associated class to app/sidedrawer/getting-started/getting-started.component.html:
```
<StackLayout>
    <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
    <Button text="OPEN DRAWER" (tap)=openDrawer()></Button>

    <Label text="This text should be blue" class="blue-style" *ngIf="!flag"></Label>
</StackLayout>
```
4) And put the flag associated on app/sidedrawer/getting-started/getting-started.component.ts:
```
export class SideDrawerGettingStartedComponent extends ObservableModule.Observable implements OnInit {

    flag: boolean = false;
```

Checkout the screenshot, as the text says it should be blue.
Remove the `*ngIf="!flag"` and you will see it blue.

![simulator screen shot jul 13 2016 20 03 52](https://cloud.githubusercontent.com/assets/15932965/16822749/0b9eccb4-4935-11e6-8557-75f54c961e02.png)

**Comment by VladimirAmiorkov** [comment]
Hi @ignaciolarranaga ,

Thank you for reporting this to us. We have been working hard in fixing a lot issues in the [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui)/[nativescript-telerik-ui-pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro) and [nativescript-angular](https://www.npmjs.com/package/nativescript-angular), I tested the described scenario with the latest nativescript-telerik-ui **1.3.1**, nativescript-angular **0.3.0** and nativescript **2.2.1** setup and all was well, The css class style is being applied correctly on both iOS and Android. It looks like this issue is related to the closed https://github.com/telerik/nativescript-ui-samples-angular/issues/13 

Could you upgrade to the latest nativescript-telerik-ui, nativescript-angular, nativescript and let us know if the issue persists. I will close the issue for now.
