### ISSUE TITLE
Cannot find module 'nativescript-telerik-ui/listview/angular/listview-directives'

### ISSUE THREAD

**Issue by rrcoolp** [telerik/nativescript-ui-samples-angular#2]
error TS2307: Cannot find module 'nativescript-telerik-ui/listview/angular/listview-directives'

**Comment by ngydat** [comment]
#1 Guess all the components of the module have the same issue. Maybe we have to wait for an update so a Typescript definition file (*.d.ts) will be available

**Comment by VladimirAmiorkov** [comment]
Hi,

We have reviewed this issue and we are already working on resolving it in our next release of Telerik UI for NativeScript.

**Comment by VladimirAmiorkov** [comment]
If you want to manually resolve this issue please refer this comment: https://github.com/telerik/nativescript-ui-samples-angular/issues/1#issuecomment-221564287

**Comment by rrcoolp** [comment]
Hello @VladimirAmiorkov,

Today I was upgrading from Angular2 to @Angular_rc1 - and started having issues with the UI modules.

Here's a paste of the error: Failed to find module "@angular/src/core/di"

Let me know if you have ideas on how to fix this. Appreciated and thanks again.

**Comment by VladimirAmiorkov** [comment]
Hi @rrcoolp ,

The current 1.1.1 version of nativescript-telerik-ui was implemented before the angular RC1 version was released which is why it is not compatible with it. 

As mentioned here https://github.com/telerik/nativescript-ui-samples-angular/issues/1#issuecomment-223590570 we have been working on upgrading the nativescript-telerik-ui to support the latest angular RC1 and you can expect a release a the new version in the incoming days so stay tuned.

**Comment by VladimirAmiorkov** [comment]
Fixed with [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) **1.2.0**
