### ISSUE TITLE
RadSideDrawer with RadListView as child not showing

### ISSUE THREAD

**Issue by kn4rfy** [telerik/nativescript-ui-samples-angular#25]
I used RadListView as a child of RadSideDrawer but it doesn't show up.

I only got this warning on console:

`Aug 10 16:45:17 kn4rfy [4158]: CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:364:14: The TypeScript constructor "TKListViewDataSourceImpl" will not be executed.
Aug 10 16:45:17 kn4rfy [4158]: CONSOLE WARN file:///app/tns_modules/nativescript-telerik-ui/listview/listview.js:505:14: The TypeScript constructor "ExtendedListViewCell" will not be executed.`

**Comment by VladimirAmiorkov** [comment]
Hi @kn4rfy ,

There was an know issue in the 1.2.0 version of nativescript-telerik-ui when placing the RadListView element inside the RadSideDrawer inAngular {N} applications. This issue was related to this one https://github.com/telerik/nativescript-ui-samples-angular/issues/13 which has been fixed in the **1.3.1** version.
