### ISSUE TITLE
global.moduleMerge is not a function

### ISSUE THREAD

**Issue by metzc** [telerik/nativescript-ui-samples-angular#3]
The iOS emulator fails with that error message
`file:///app/tns_modules/application/application-common.js:5:19: JS ERROR TypeError: global.moduleMerge is not a function. (In 'global.moduleMerge(events, exports)', 'global.moduleMerge' is undefined)`

Fresh checkout of release branch
cd sdkAngular
npm install
tns emulate iOS

Am i missing something?

**Comment by anhoev** [comment]
I have the same problem, any plan for fix ?

**Comment by VladimirAmiorkov** [comment]
Hi @metzc and @anhoev ,

I just tried to reproduce the mentioned error massage by running the `tns emulate ios` on the release branch and the build was successful. Can you try to clear the **platforms** and **node_modules** folders and do a clear `tns emulate ios` on the release brach just to make sure the error was not caused by local cache. If the error massage (displayed in the terminal/cmd) still occurs could you paste the entire terminal contents in order for me to further investigate it.

**Comment by arnaudvalle** [comment]
@VladimirAmiorkov I had the same issue and doing what you said actually fixed it for me. Thanks!

**Comment by giangdm** [comment]
I had the same issue, and after long time I discovery that in **node_modules** has a library with name **globals version ^8.3.0** (babel-traverse depend it).
And the tns-core-modules has a library same name **globals**.

After views output directory in apk **.../files/app/tns-modules/globals** I realized all files is combine from 2 above folder.

After uninstall **globals version ^8.3.0**, and valid all depend libary of babel-traverse already install inside the issue is gone out.

**Comment by shlomiassaf** [comment]
@VladimirAmiorkov 

This is not solved, the error is due to NPM3 and how it install dependencies.

If the CLI put's the content of `tns-core-modules` in `tns-modules` and **copies** all other related packages from `node_modules` it just a matter of time until another error comes to life.

A workaround it to `npm install --legacy-bundling` but that's temporary.

The structure is invalid in NativeScript since npm 3.0 is going to stay.
