### ISSUE TITLE
Error with Multiple ListView (SideDrawer too)

### ISSUE THREAD

**Issue by eleddie** [telerik/nativescript-ui-samples-angular#43]
I manage to get the listview and the sidedrawer working in one component, but if I want to have many components with different listviews I have to move the directives declarations (which I had in the component NgModule) to the root NgModule. 
But then the list doesn't show... 

Any help with this? I need multiple lists in different components.

**Comment by VladimirAmiorkov** [comment]
Hi @eleddie ,

I am not sure I understand you correctly. By design in order to use the **RadListView** and **RadSIdeDrawer** components of the nativescript-telerik-ui plugin in Angular 2 app all that you need to do is import the `LISTVIEW_DIRECTIVES` and `SIDEDRAWER_DIRECTIVES` and pass the to your app's initial (bootstrap) `@NgModule`. After that you can freely use the related RadListView and RadSideDrawer directives in any other Angular 2 `@Component` of your app.

You can find more information regarding the bootstrap process in our documentation [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started).
