### ISSUE TITLE
Drawer breaks after navigating to another page

### ISSUE THREAD

**Issue by ntrp** [telerik/nativescript-ui-samples-angular#46]
The drawer is working perfectly when I open the home page but as soon as I navigate to any page using the page-router-outlet it breaks, even if I go back to home the drawer doesn´t work anymore.

### Which platform(s) does your issue occur on?
Tested only Android (7.0.0, 6.0.1, 5.1.1)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): 2.3.0
- Plugin(s): n/a

### Please tell us how to recreate the issue in as much detail as possible.
example project at:
https://github.com/ntrp/nativescript-ng2-drawer-seed/tree/latest-exp

Just clone, install and run. Then open the drawer and navigate to the ToDo page.

**Comment by VladimirAmiorkov** [comment]
Hi @ntrp ,

Thank you for reporting this to us. The issue in the [mentioned project](showOverNavigation) is caused by the use of the `showOverNavigation` in an {N} + Angular 2 application. Currently the "over navigation/ActionBar" feature is not available in an Angular 2 application. Simple remove the setter for that property from [here](https://github.com/ntrp/nativescript-ng2-drawer-seed/blob/latest-exp/app/components/page.component.ts#L16) and the RadSideDrawer will perform as expected. For more information regarding this feature you can follow this thread: https://github.com/telerik/nativescript-ui-samples-angular/issues/26
